CREATE TABLE ACCOUNT
(
    ID INTEGER NOT NULL,
    ACCOUNT_NUMBER VARCHAR(20) NOT NULL,
    BALANCE INTEGER NOT NULL
);
CREATE TABLE ADMIN
(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    LOGIN VARCHAR(32) NOT NULL,
    PASSWORD VARCHAR(32) NOT NULL,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL
);
CREATE TABLE CLIENT
(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    LOGIN VARCHAR(32) NOT NULL,
    PASSWORD VARCHAR(32) NOT NULL,
    BILL DECIMAL(65535,32767) DEFAULT 0 NOT NULL
);
CREATE TABLE DISPATCHER
(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    LOGIN VARCHAR(32) NOT NULL,
    PASSWORD VARCHAR(32) NOT NULL,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    NATIONAL_ID VARCHAR(13) NOT NULL,
    PHONE VARCHAR(20) NOT NULL
);
CREATE TABLE DRIVER
(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    LOGIN VARCHAR(32) NOT NULL,
    PASSWORD VARCHAR(32) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    FIRST_NAME VARCHAR(50) NOT NULL,
    NATIONAL_ID VARCHAR(13) NOT NULL,
    PHONE VARCHAR(32) NOT NULL,
    AVAILABLE BOOLEAN DEFAULT TRUE NOT NULL,
    CURRENT_LOCATION VARCHAR(100),
    GOV_NUMBER VARCHAR(15),
    CAR_MODEL VARCHAR(100),
    CAR_CLASS VARCHAR(32),
    CAR_STATE VARCHAR(50),
    CAR_IMAGE VARCHAR(200)
);
CREATE TABLE ORDERS
(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    CLIENT_ID BIGINT NOT NULL,
    CAR_CLASS VARCHAR(50),
    PICKUP_LOCATION VARCHAR(100),
    DROP_OFF_LOCATION VARCHAR(100),
    RECEIVED_TIME TIMESTAMP DEFAULT NOW() NOT NULL,
    DRIVER_ID BIGINT,
    COST DECIMAL(65535,32767),
    STATUS_ID INTEGER
);
CREATE TABLE STATUS
(
    ID INTEGER PRIMARY KEY NOT NULL,
    VALUE VARCHAR(32) NOT NULL
);
CREATE UNIQUE INDEX UNIQUE_LOGIN_INDEX_4 ON DISPATCHER (LOGIN);
CREATE UNIQUE INDEX UNIQUE_NATIONAL_ID_INDEX_4 ON DISPATCHER (NATIONAL_ID);
CREATE INDEX "CURRENT_LOCATION_index" ON DRIVER (CURRENT_LOCATION);
ALTER TABLE ORDERS ADD FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT (ID);
ALTER TABLE ORDERS ADD FOREIGN KEY (DRIVER_ID) REFERENCES DRIVER (ID);
ALTER TABLE ORDERS ADD FOREIGN KEY (STATUS_ID) REFERENCES STATUS (ID);
